config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'billboards#index'
  #only: [:billboards, :artists]
  resources :billboards do
    resources :artists
  end

  resources :artists do
    resources :songs
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :top_artist, dependent: :destroy
  validates :top_artist, :most_played_song, :albums_sold, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :top_artist

  validates :album, :title, :year_of_release, :plays, presence: true

  validates :title, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
    
  end

  def show
    
  end
  
 # ADD THE FOLLOWING METHOD/ACTIONS BELOW

  def new
    
  end

  def create
    
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


  def index
    @artist = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(Artist_params)
    if @artist.save
      redirect_to artists_path #############
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(Artist_params)
      redirect_to artists_path ############
    else
      render :edit
    end
  end

  def destroy
    Artist.find(params[:id]).destroy
    redirect_to artists_path
  end

  private
    def Artist_params 
      params.require(:artist).permit(:name, :genre, :subscribers, :debut)
    end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all
  end

  def show
    @billboard = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
  end

  def edit
    @billboard = Billboard.find(params[:id])
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to @billboard
    else
      render :new
    end
  end

  def update
    @billboard = Billboard.find(params[:id])
    if @billboard.update(billboard_params)
      redirect_to billboards_path ############
    else
      render :edit
    end
  end

  def destroy
    Billboard.find(params[:id]).destroy
    redirect_to billboards_path
  end

  private
    def billboard_params 
      params.require(:billboard).permit(:artist, :most_played_song, :albums_sold)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @song = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def edit
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(Song_params)
    if @song.save
      redirect_to billboard_path #############
    else
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(Song_params)
      redirect_to song_path ############
    else
      render :edit
    end
  end

  def destroy
    Song.find(params[:id]).destroy
    redirect_to songs_path
  end

  private
    def Song_params 
      params.require(:song).permit(:title, :album, :year_of_release, :plays)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists</h1>


<ul>
  <% @artist.each do |artist| %>
    <li>
      <%= link_to billboard.artist, [@billboard, artist] %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create Artist', new_billboard_artist_path(:billboard_id) %>

app/views/artists/new.html.erb
<h1>Artist Entry</h1>

<%= form_with(model: @artist, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre, required: true %>
  </div>
  <br />
  <div class="field">
  <%= f.label :subscribers %>
  <%= f.text_field :subscribers, required: true %>
</div>
<br/>
<div class="field">
  <%= f.label :debut %>
  <%= f.text_field :debut, required: true %>
</div>
<br/>
  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<hr />
<h2>Songs</h2>
<ul>
  <% @artist.songs.each do |song| %>
    <li>
    <%= link_to song.name, song %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Show Billboard Top 100', billboard_path %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboard Top 100</h1>


<ul>
  <% @billboards.each do |billboard| %>
    <li>
      <%= link_to billboard.artist, billboard %>
    </li>
  <% end %>
</ul>
<%= link_to 'New Billboard', new_billboard_path %>
<br />
<%= link_to 'Billboards', billboard_path(:billboard_id) %>

<br />
<%= link_to 'Artists', billboard_artists_path(:artist_id) %>
<br />

<%= link_to 'Songs', artist_songs_path(:song_id) %>

app/views/billboards/new.html.erb
<h1>New Billboard Entry</h1>

<%= form_with(model: @billboard, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist, required: true, autofocus: true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :song %>
    <%= f.text_field :most_played_song, required: true %>
  </div>
  <br />
  <div class="field">
  <%= f.label :albums_Sold %>
  <%= f.text_field :albums_sold, required: true %>
</div>
<br/>
  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopBillboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs</h1>

<ul>
  <% @song.each do |song| %>
    <li>
      <%= link_to artist.song, artist %>
    </li>
  <% end %>
</ul>
<%= link_to 'Create Song', new_artist_song_path(:song_id) %>

app/views/songs/new.html.erb
<h1>Songs</h1>

<%= form_with(model: @songs, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :Album %>
    <%= f.text_field :album, required: true, autofocus: true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :Title %>
    <%= f.text_field :title, required: true %>
  </div>
  <br />
  <div class="field">
    <%= f.label :Year %>
    <%= f.text_field :year_of_release, required: true %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :Plays %>
    <%= f.text_field :plays, required: true %>
  </div>
  <br/>
  <%= f.submit nil, class: 'ui green button' %>
<% end %>

app/views/songs/show.html.erb
<h1>Songs</h1>

<h1><%= @song.name %></h1>
<hr />
<h2>Courses</h2>
<ul>
  <% @user.courses.each do |course| %>
    <li>
    <%= link_to course.name, course %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Delete User', @user, method: :delete, class: 'ui red button' %>